//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub(crate) use super::{
    accounts::Entity as Accounts, folders::Entity as Folders, jobs::Entity as Jobs, sessions::Entity as Sessions, user_settings::Entity as UserSettings,
    users::Entity as Users,
};
