use chrono::{DateTime, Utc};
use derive_builder::Builder;
use mk_utils::{define_token_prefix, token::Token};

use crate::{crypto::Ciphertext, imap::ImapServerConfig, types::EmailAddress, user::UserId};

define_token_prefix!(AccountTokenPrefix, "A_");
pub type AccountId = u64;
pub type AccountToken = Token<AccountTokenPrefix, AccountId, { i64::MAX as u128 }>;

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum AccountStatus {
    PendingFirstSync,
    Syncing,
    Idle,
    Error,
    Disabled,
}

impl AccountStatus {
    /// String form used by the DB adapter (matches the migration's default
    /// literal `'PendingFirstSync'`).
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::PendingFirstSync => "PendingFirstSync",
            Self::Syncing => "Syncing",
            Self::Idle => "Idle",
            Self::Error => "Error",
            Self::Disabled => "Disabled",
        }
    }

    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "PendingFirstSync" => Some(Self::PendingFirstSync),
            "Syncing" => Some(Self::Syncing),
            "Idle" => Some(Self::Idle),
            "Error" => Some(Self::Error),
            "Disabled" => Some(Self::Disabled),
            _ => None,
        }
    }
}

/// Plaintext credential envelope. Serialized to JSON, then encrypted with
/// AAD = account_id into a `Ciphertext`. Self-describing — new auth variants
/// slot in without schema backfill.
#[derive(serde::Serialize, serde::Deserialize, Clone)]
#[non_exhaustive]
pub enum Credentials {
    Password(String),
}

/// Intentionally no `Debug` — keeps log/print sites from accidentally
/// dumping account metadata (server hostnames, usernames).
#[derive(Clone, Builder)]
pub struct Account {
    pub id: AccountId,
    pub version: u64,
    pub token: AccountToken,
    pub user_id: UserId,
    pub display_name: String,
    pub email_address: EmailAddress,
    pub server: ImapServerConfig,
    pub username: String,
    pub credentials: Ciphertext,
    #[builder(default = "true")]
    pub enabled: bool,
    #[builder(default = "AccountStatus::PendingFirstSync")]
    pub status: AccountStatus,
    #[builder(default = "None")]
    pub last_error: Option<String>,
    #[builder(default = "None")]
    pub last_synced_at: Option<DateTime<Utc>>,
    #[builder(default = "Utc::now()")]
    pub created_at: DateTime<Utc>,
    #[builder(default = "Utc::now()")]
    pub updated_at: DateTime<Utc>,
}

#[derive(Clone)]
pub struct NewAccount {
    pub user_id: UserId,
    pub display_name: String,
    pub email_address: EmailAddress,
    pub server: ImapServerConfig,
    pub username: String,
    pub credentials: Ciphertext, // pre-encrypted by service
    pub token: AccountToken,     // generated by service before encryption
}

#[derive(Default, Clone)]
pub struct PartialAccountUpdate {
    pub display_name: Option<String>,
    pub credentials: Option<Ciphertext>, // pre-encrypted by service
    pub server: Option<ImapServerConfig>,
    pub username: Option<String>,
}

impl PartialAccountUpdate {
    pub fn apply_to(self, account: &mut Account) {
        if let Some(v) = self.display_name {
            account.display_name = v;
        }
        if let Some(v) = self.credentials {
            account.credentials = v;
        }
        if let Some(v) = self.server {
            account.server = v;
        }
        if let Some(v) = self.username {
            account.username = v;
        }
    }

    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.display_name.is_none() && self.credentials.is_none() && self.server.is_none() && self.username.is_none()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::imap::TlsMode;

    fn fake_ct() -> Ciphertext {
        Ciphertext::from_raw(vec![0u8; 28])
    }

    fn fake_account() -> Account {
        AccountBuilder::default()
            .id(1)
            .version(0)
            .token(AccountToken::new(1))
            .user_id(42)
            .display_name("Test".to_string())
            .email_address(EmailAddress::new("a@b.com").unwrap())
            .server(ImapServerConfig {
                host: "imap.example.com".into(),
                port: 993,
                tls: TlsMode::Tls,
            })
            .username("a@b.com".to_string())
            .credentials(fake_ct())
            .build()
            .unwrap()
    }

    #[test]
    fn credentials_password_json_round_trip() {
        let creds = Credentials::Password("hunter2".to_string());
        let json = serde_json::to_vec(&creds).expect("serialize");
        let back: Credentials = serde_json::from_slice(&json).expect("deserialize");
        match back {
            Credentials::Password(p) => assert_eq!(p, "hunter2"),
        }
    }

    #[test]
    fn account_status_round_trip() {
        for s in [
            AccountStatus::PendingFirstSync,
            AccountStatus::Syncing,
            AccountStatus::Idle,
            AccountStatus::Error,
            AccountStatus::Disabled,
        ] {
            assert_eq!(AccountStatus::from_str(s.as_str()), Some(s));
        }
        assert!(AccountStatus::from_str("Bogus").is_none());
    }

    #[test]
    fn account_token_id_matches_account_id() {
        let token = AccountToken::generate();
        let id: AccountId = token.id();
        assert!(id > 0);
    }

    #[test]
    fn account_token_display_starts_with_a_prefix() {
        let token = AccountToken::generate();
        assert!(token.to_string().starts_with("A_"));
    }

    #[test]
    fn account_builder_defaults_enabled_true_status_pending() {
        let a = fake_account();
        assert!(a.enabled);
        assert_eq!(a.status, AccountStatus::PendingFirstSync);
        assert!(a.last_error.is_none());
        assert!(a.last_synced_at.is_none());
    }

    #[test]
    fn partial_update_is_empty_all_none() {
        assert!(PartialAccountUpdate::default().is_empty());
    }

    #[test]
    fn partial_update_is_empty_display_some() {
        let u = PartialAccountUpdate {
            display_name: Some("X".into()),
            ..Default::default()
        };
        assert!(!u.is_empty());
    }

    #[test]
    fn partial_update_apply_to_updates_only_some_fields() {
        let mut a = fake_account();
        let u = PartialAccountUpdate {
            display_name: Some("New Name".into()),
            ..Default::default()
        };
        u.apply_to(&mut a);
        assert_eq!(a.display_name, "New Name");
        assert_eq!(a.server.host, "imap.example.com");
    }

    #[test]
    fn partial_update_apply_to_replaces_credentials() {
        let mut a = fake_account();
        let new_ct = Ciphertext::from_raw(vec![1u8; 28]);
        let u = PartialAccountUpdate {
            credentials: Some(new_ct.clone()),
            ..Default::default()
        };
        u.apply_to(&mut a);
        assert_eq!(a.credentials.as_bytes(), new_ct.as_bytes());
    }
}
