[tools]
"buf" = "1.72.0"
"cargo:cargo-audit" = "0.22.2"
"cargo:cargo-deny" = "0.20.2"
"cargo:cargo-insta" = "1.48.0"
"cargo:cargo-nextest" = "0.9.143"
"cargo:dioxus-cli" = "0.7.10"
"cargo:mdbook" = "0.5.4"
"colima" = "0.10.3"
"git-cliff" = "2.14.1"
"npm:tailwindcss" = "4.3.3"
"prettier" = "3.9.6"
"protobuf" = "36.0"
"tailwindcss" = "4.2.1"

[tool_alias]
tailwindcss = "github:tailwindlabs/tailwindcss"
