use std::{any::Any, pin::Pin, sync::Arc};

use derive_builder::Builder;

use crate::{
    Error,
    auth::SessionRepository,
    user::{UserRepository, UserSettingRepository},
};

#[derive(Builder)]
#[builder(pattern = "owned")]
pub struct RepositoryService {
    repository: Arc<dyn Repository>,
    session_repository: Arc<dyn SessionRepository>,
    user_repository: Arc<dyn UserRepository>,
    user_setting_repository: Arc<dyn UserSettingRepository>,
}

impl RepositoryService {
    /// Returns a reference to the main repository for transaction management.
    #[must_use]
    pub fn repository(&self) -> &Arc<dyn Repository> {
        &self.repository
    }

    /// Returns a reference to the session repository.
    #[must_use]
    pub fn session_repository(&self) -> &Arc<dyn SessionRepository> {
        &self.session_repository
    }

    /// Returns a reference to the user repository.
    #[must_use]
    pub fn user_repository(&self) -> &Arc<dyn UserRepository> {
        &self.user_repository
    }

    /// Returns a reference to the user setting repository.
    #[must_use]
    pub fn user_setting_repository(&self) -> &Arc<dyn UserSettingRepository> {
        &self.user_setting_repository
    }
}

#[async_trait::async_trait]
pub trait Transaction: Any + Send + Sync {
    fn as_any(&self) -> &dyn Any;
    async fn commit(self: Box<Self>) -> Result<(), Error>;
    async fn rollback(self: Box<Self>) -> Result<(), Error>;
}

/// Execute an async operation within a read-write transaction.
///
/// Clones one or more repositories, begins a transaction, executes the body,
/// and commits on success or rolls back on error.
///
/// # Examples
/// ```ignore
/// // Single repository
/// with_transaction!(self, user_repository, |tx| {
///     user_repository.add_user(tx, user).await
/// })
///
/// // Multiple repositories
/// with_transaction!(self, user_repository, order_repository, |tx| {
///     let user = user_repository.add_user(tx, user).await?;
///     order_repository.create_order(tx, user.id, order).await
/// })
/// ```
#[macro_export]
macro_rules! with_transaction {
    ($self:expr, $($repo:ident),+ , |$tx:ident| $body:expr) => {{
        $(let $repo = $self.repository_service.$repo().clone();)+
        $crate::repository::transaction(&**$self.repository_service.repository(), |$tx| Box::pin(async move { $body })).await
    }};
}

/// Execute an async operation within a read-only transaction.
///
/// Clones one or more repositories and executes the body within a read-only
/// transaction.
///
/// # Examples
/// ```ignore
/// // Single repository
/// with_read_only_transaction!(self, user_repository, |tx| {
///     user_repository.find_by_id(tx, id).await
/// })
///
/// // Multiple repositories
/// with_read_only_transaction!(self, user_repository, order_repository, |tx| {
///     let user = user_repository.find_by_id(tx, id).await?;
///     let orders = order_repository.find_by_user(tx, user.id).await?;
///     Ok((user, orders))
/// })
/// ```
#[macro_export]
macro_rules! with_read_only_transaction {
    ($self:expr, $($repo:ident),+ , |$tx:ident| $body:expr) => {{
        $(let $repo = $self.repository_service.$repo().clone();)+
        $crate::repository::read_only_transaction(&**$self.repository_service.repository(), |$tx| Box::pin(async move { $body })).await
    }};
}

#[async_trait::async_trait]
#[cfg_attr(test, mockall::automock)]
#[allow(unused_lifetimes, reason = "Generated by mockall")]
pub trait Repository: Send + Sync {
    async fn begin(&self) -> Result<Box<dyn Transaction>, Error>;
    async fn begin_read_only(&self) -> Result<Box<dyn Transaction>, Error>;
    async fn close(&self) -> Result<(), Error>;
    /// Verify the DB connection is alive. Used by `ResilienceWrapper::check()`.
    async fn ping(&self) -> Result<(), Error>;
}

/// Execute a closure within a transaction, automatically committing on success
/// or rolling back on error.
///
/// # Example
/// ```ignore
/// let result = transaction(&*repository, |tx| Box::pin(async move {
///     // do stuff with tx
///     Ok(result)
/// })).await?;
/// ```
pub async fn transaction<F, T>(repository: &dyn Repository, callback: F) -> Result<T, Error>
where
    F: for<'c> FnOnce(&'c dyn Transaction) -> Pin<Box<dyn Future<Output = Result<T, Error>> + Send + 'c>> + Send,
    T: Send,
{
    let tx = repository.begin().await?;
    match callback(&*tx).await {
        Ok(result) => {
            tx.commit().await?;
            Ok(result)
        }
        Err(e) => {
            // Best effort rollback - if it fails, we still return the original error
            let _ = tx.rollback().await;
            Err(e)
        }
    }
}

/// Execute a closure within a read-only transaction.
///
/// # Example
/// ```ignore
/// let result = read_only_transaction(&*repository, |tx| Box::pin(async move {
///     // do stuff with tx
///     Ok(result)
/// })).await?;
/// ```
pub async fn read_only_transaction<F, T>(repository: &dyn Repository, callback: F) -> Result<T, Error>
where
    F: for<'c> FnOnce(&'c dyn Transaction) -> Pin<Box<dyn Future<Output = Result<T, Error>> + Send + 'c>> + Send,
    T: Send,
{
    let tx = repository.begin_read_only().await?;
    callback(&*tx).await
}

/// Shared test helpers for building a fully-mocked `RepositoryService`.
#[cfg(test)]
pub(crate) mod testing {
    use std::{any::Any, sync::Arc};

    use super::{MockRepository, RepositoryServiceBuilder, Transaction};
    use crate::{
        Error,
        auth::repository::MockSessionRepository,
        user::repository::{user::MockUserRepository, user_settings::MockUserSettingRepository},
    };

    /// A no-op transaction for unit tests.
    pub(crate) struct MockTransaction;

    #[async_trait::async_trait]
    impl Transaction for MockTransaction {
        fn as_any(&self) -> &dyn Any {
            self
        }

        async fn commit(self: Box<Self>) -> Result<(), Error> {
            Ok(())
        }

        async fn rollback(self: Box<Self>) -> Result<(), Error> {
            Ok(())
        }
    }

    /// Returns a `MockRepository` pre-configured to open transactions.
    pub(crate) fn make_mock_repo() -> MockRepository {
        let mut r = MockRepository::new();
        r.expect_begin()
            .returning(|| Box::pin(async { Ok(Box::new(MockTransaction) as Box<dyn Transaction>) }));
        r.expect_begin_read_only()
            .returning(|| Box::pin(async { Ok(Box::new(MockTransaction) as Box<dyn Transaction>) }));
        r.expect_ping().returning(|| Box::pin(async { Ok(()) }));
        r
    }

    /// Returns a `RepositoryServiceBuilder` pre-populated with default mocks
    /// for all repositories. Override individual fields for the repo(s) under
    /// test before calling `.build()`.
    pub(crate) fn default_repository_service_builder() -> RepositoryServiceBuilder {
        RepositoryServiceBuilder::default()
            .repository(Arc::new(make_mock_repo()))
            .session_repository(Arc::new(MockSessionRepository::new()))
            .user_repository(Arc::new(MockUserRepository::new()))
            .user_setting_repository(Arc::new(MockUserSettingRepository::new()))
    }
}
