name: Remove Docker Tag

on:
  workflow_dispatch:

jobs:
  remove-docker-tag:
    runs-on: ubuntu-latest

    # Sets the permissions granted to the `GHCR_TOKEN` for the actions in this job.
    # (required)
    permissions:
      contents: read
      packages: write

    steps:
      - name: Remove Docker Tag
        uses: rafalkk/remove-dockertag-action@581f14f26a4a127cbe4145f7584975483a58b4e8 # v1
        with:
          tag_name: v0.10.0
          github_token: ${{ secrets.GHCR_TOKEN }}
